// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
class Routes {
  const Routes._();

  /// '/routeNew'
  ///
  /// [name] : '/routeNew'
  ///
  /// [showStatusBar] : false
  static const String routeNew = '/routeNew';

  /// 'RouterArg'
  ///
  /// [name] : '/routerArg'
  ///
  /// [routeName] : 'RouterArg'
  ///
  /// [constructors] :
  ///
  /// RouterArg : [Key key, int value, String text, Avs avsModel]
  static const String routerArg = '/routerArg';

  /// 'RouterNotArg'
  ///
  /// [name] : '/routerNotArg'
  ///
  /// [routeName] : 'RouterNotArg'
  static const String routerNotArg = '/routerNotArg';
}
